### ISSUE TITLE
Neues Namensschema

### ISSUE THREAD

**Issue by quotengrote** [quotengrote/dp_ausb_md#112]
Da in Zukunft ja nur noch ein Rack geplant ist, macht unser derzeitges(und eh nicht angewendetes) Namensschema für Computer keinen Sinn mehr.

## Vorschlag:
B/S/T - Basisdienst oder Schulung oder Test
L/W/A - Linux/Windows/Appliance
4-Stellen Bezeichnung - z.B. dnsm
3-Stellige Nummer - 001

## Beispiel
```BLDNSM001``` wäre dann ein DNSMasq des Basisdienstes, betrieben auf Linux mit der Nummer 001

**Comment by quotengrote** [comment]
Die bestehnden VM-Bezeichnungen und Hostnamen müssen dann angepasst werden.

**Comment by Kati-20DP** [comment]
Können wir gern so machen.
