### ISSUE TITLE
Auslagerung Doku zu Github-Wiki

### ISSUE THREAD

**Issue by DanielMueller1309** [quotengrote/dp_ausb_md#224]
- [ ] Umzug fertig...

Vorschlag: wir lagern alles außer ansible und Scripte aus dem Code Bereich aus und schreiben sie in den Bereich Wiki. Einziger Nachteile Branches können zwar erstellt werden aber nicht als PR zum prüfen online gestellt werden

**Comment by MaxGoe** [comment]
ist dadurch deutlich übersichtlicher und angenehmer zu lesen mMn. ob der extra Aufwand das Ergebnis rechtfertigt ist Ansichtssache was sagen die Anderen

**Comment by quotengrote** [comment]
+1
