### ISSUE TITLE
initiale Workflow-Anpassung

### ISSUE THREAD

**Issue by DanielMueller1309** [quotengrote/dp_ausb_md#74]
Also mein Vorschlag wäre es dem Bootstrap-Playbook eine weitere rolle für die Proxmox hosts hinzu zu fügen welche dafür sorgen das die nötigen VMs (später auch gerne Container) beim Initialen bootstrapen mit den passenden hostnamen aufgesetzt werden bzw aus einem Template geklont werden und dabei einen Hostnamen bekommen. Das modul [community.general.proxmox](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html) unterstützt dies zum glück um weiter auf das wissen von IPs zu verzichten und nur auf FQDNs zu setzen. Der DHCP müsste dann natürlich als erstes Playbook nach der Bootstrap ausgeführt werden um IPs zu verteilen und vom DHCP (zugleich ja DNS) die hostnamen ein zu sammeln um beim ausführen der anderen playbooks die passenden IPs zu den FQDNs im Inventory zu bekommen.  
Der Vorteil dieser extra rolle liegt somit darin das wir nur noch ein initiales Template brauchen welches entweder in einem weiteren schritt auch per Ansible aufgesetzt wird oder neben der Installation der Proxmox Hosts nur einmal händisch erstellt werden muss und somit nicht jede VM händisch  aus einem Template geklont werden muss. Heist stirbt uns die Hardware mal wieder und wir müssen von vorne anfangen hat man dadurch noch weniger Arbeit als bisher (aka alles zu tode automatisieren 😃  )

**Comment by quotengrote** [comment]
@DanielMueller1309 ?
