### ISSUE TITLE
Fehlermeldung bei löschen (+ purgen)einer VM

### ISSUE THREAD

**Issue by quotengrote** [quotengrote/dp_ausb_md#98]
folgende Meldung erschien als ich einen hacken bei purge setzte:

Parameter verification failed. (400)

purge: property is not defined in schema and the schema does not allow additional properties

**Comment by quotengrote** [comment]
Beitrag im Forum erstellt

**Comment by quotengrote** [comment]
@MaxGoe Kannst du noch den Link zum Eintrag hier posten?

**Comment by MaxGoe** [comment]
https://forum.proxmox.com/threads/error-when-purging-vm.88781/#post-388822

**Comment by MaxGoe** [comment]
Habe Forum Mitarbeiter privat angeschrieben vor ca. 6 Tagen und noch keine Antwort erhalten.

**Comment by DanielMueller1309** [comment]
root@RMPHLPVE2:~# pveversion -v
proxmox-ve: 6.0-2 (running kernel: 5.0.15-1-pve)
pve-manager: 6.0-4 (running version: 6.0-4/2a719255)
pve-kernel-5.0: 6.0-5
pve-kernel-helper: 6.0-5
pve-kernel-5.0.15-1-pve: 5.0.15-1
ceph-fuse: 12.2.11+dfsg1-2.1+b1
corosync: 3.0.2-pve2
criu: 3.11-3
glusterfs-client: 5.5-3
ksm-control-daemon: 1.3-1
libjs-extjs: 6.0.1-10
libknet1: 1.10-pve1
libpve-access-control: 6.0-2
libpve-apiclient-perl: 3.0-2
libpve-common-perl: 6.0-2
libpve-guest-common-perl: 3.0-1
libpve-http-server-perl: 3.0-2
libpve-storage-perl: 6.0-5
libqb0: 1.0.5-1
lvm2: 2.03.02-pve3
lxc-pve: 3.1.0-61
lxcfs: 3.0.3-pve60
novnc-pve: 1.0.0-60
proxmox-mini-journalreader: 1.1-1
proxmox-widget-toolkit: 2.0-5
pve-cluster: 6.0-4
pve-container: 3.0-3
pve-docs: 6.0-4
pve-edk2-firmware: 2.20190614-1
pve-firewall: 4.0-5
pve-firmware: 3.0-2
pve-ha-manager: 3.0-2
pve-i18n: 2.0-2
pve-qemu-kvm: 4.0.0-3
pve-xtermjs: 3.13.2-1
qemu-server: 6.0-5
smartmontools: 7.0-pve2
spiceterm: 3.1-1
vncterm: 1.6-1
zfsutils-linux: 0.8.1-pve1






root@RMPHLPVE2:~# qm config 106
user config - ignore config line: token:root@pam!cv4pve:0:0:f%C3%BCr automatisierte snapshots:
agent: 1
bootdisk: scsi0
cores: 2
ide2: none,media=cdrom
memory: 2048
name: SLTEST001
net0: virtio=CA:00:73:1D:51:1D,bridge=vmbr2
numa: 0
ostype: l26
parent: TestVM
scsi0: local-lvm:vm-106-disk-0,discard=on,size=8G
scsihw: virtio-scsi-pci
smbios1: uuid=695962f0-52d2-4d39-9d7b-1cbdcdf5d60d
sockets: 1
vmgenid: 00810ee7-8c23-4774-aaa8-d41b4b62cf11

**Comment by DanielMueller1309** [comment]
user@RMPHLPVE2:/var/lib$ sudo qm destroy 106 --purge
Unknown option: purge
400 unable to parse option
qm destroy <vmid> [OPTIONS]
user@RMPHLPVE2:/var/lib$ sudo qm destroy 106 --skiplock 1
file /etc/pve/storage.cfg line 4 (section 'local') - unable to parse value of 'prune-backups': unexpected property 'prune-backups'
  Logical volume "snap_vm-106-disk-0_TestVM" successfully removed
  Logical volume "vm-106-disk-0" successfully removed
  Logical volume "vm-106-state-TestVM" successfully removed
user@RMPHLPVE2:/var/lib$

**Comment by MaxGoe** [comment]
Upgrade/Update auf Node ausführen  (Siehe Forenbeitrag) bitte Ausgabe wieder hier reinschreiben sodass ich im Forum antworten kann. @DanielMueller1309 @quotengrote

**Comment by quotengrote** [comment]
@MaxGoe 

Update ist durch:
neuer Status: Auswahl Purge nicht mehr vorhanden
![2021-05-26 15_01_10-Greenshot](https://user-images.githubusercontent.com/38253905/119664100-4a0e6900-be33-11eb-822b-9f40975dee84.png)

Logmeldung:
`May 26 15:00:03 RMPHLPVE2 pvedaemon[29923]: file /etc/pve/storage.cfg line 4 (section 'local') - unable to parse value of 'prune-backups': unexpected property 'prune-backups'`

**Comment by quotengrote** [comment]
Korrektur, nach durchstarten vom kompletten Cluster
![2021-05-26 15_13_05-Greenshot](https://user-images.githubusercontent.com/38253905/119665731-f69d1a80-be34-11eb-8ba8-2a47ddae800f.png)
![2021-05-26 15_13_14-Greenshot](https://user-images.githubusercontent.com/38253905/119665735-f7ce4780-be34-11eb-8d13-5a7ebfafa451.png)

**Comment by quotengrote** [comment]
Ähnlicher Fehler auch beim Backup
`INFO: starting new backup job: vzdump --mailnotification always --storage local --quiet 1 --all 1 --node RMPHLPVE2 --mode snapshot --compress gzip
INFO: Starting Backup of VM 100 (qemu)
INFO: Backup started at 2021-06-09 09:46:52
INFO: status = running
INFO: file /etc/pve/storage.cfg line 4 (section 'local') - unable to parse value of 'prune-backups': unexpected property 'prune-backups'`

@MaxGoe wie ist der aktuelle Stand?

**Comment by quotengrote** [comment]
`mg@RMPHLPVE2:~$ pveversion -v
proxmox-ve: 6.0-2 (running kernel: 5.0.15-1-pve)
pve-manager: 6.0-4 (running version: 6.0-4/2a719255)
pve-kernel-5.0: 6.0-5
pve-kernel-helper: 6.0-5
pve-kernel-5.0.15-1-pve: 5.0.15-1
ceph-fuse: 12.2.11+dfsg1-2.1+b1
corosync: 3.0.2-pve2
criu: 3.11-3
glusterfs-client: 5.5-3
ksm-control-daemon: 1.3-1
libjs-extjs: 6.0.1-10
libknet1: 1.10-pve1
libpve-access-control: 6.0-2
libpve-apiclient-perl: 3.0-2
libpve-common-perl: 6.0-2
libpve-guest-common-perl: 3.0-1
libpve-http-server-perl: 3.0-2
libpve-storage-perl: 6.0-5
libqb0: 1.0.5-1
lvm2: 2.03.02-pve3
lxc-pve: 3.1.0-61
lxcfs: 3.0.3-pve60
novnc-pve: 1.0.0-60
proxmox-mini-journalreader: 1.1-1
proxmox-widget-toolkit: 2.0-5
pve-cluster: 6.0-4
pve-container: 3.0-3
pve-docs: 6.0-4
pve-edk2-firmware: 2.20190614-1
pve-firewall: 4.0-5
pve-firmware: 3.0-2
pve-ha-manager: 3.0-2
pve-i18n: 2.0-2
pve-qemu-kvm: 4.0.0-3
pve-xtermjs: 3.13.2-1
qemu-server: 6.0-5
smartmontools: 7.0-pve2
spiceterm: 3.1-1
vncterm: 1.6-1
zfsutils-linux: 0.8.1-pve1`


`mg@RMPHLPVE1:~$ pveversion -v
proxmox-ve: 6.4-1 (running kernel: 5.4.114-1-pve)
pve-manager: 6.4-8 (running version: 6.4-8/185e14db)
pve-kernel-5.4: 6.4-2
pve-kernel-helper: 6.4-2
pve-kernel-5.0: 6.0-11
pve-kernel-5.4.114-1-pve: 5.4.114-1
pve-kernel-5.4.106-1-pve: 5.4.106-1
pve-kernel-5.0.21-5-pve: 5.0.21-10
pve-kernel-5.0.15-1-pve: 5.0.15-1
ceph-fuse: 12.2.11+dfsg1-2.1+b1
corosync: 3.1.2-pve1
criu: 3.11-3
glusterfs-client: 5.5-3
ifupdown: residual config
ifupdown2: 3.0.0-1+pve3
ksm-control-daemon: 1.3-1
libjs-extjs: 6.0.1-10
libknet1: 1.20-pve1
libproxmox-acme-perl: 1.1.0
libproxmox-backup-qemu0: 1.0.3-1
libpve-access-control: 6.4-1
libpve-apiclient-perl: 3.1-3
libpve-common-perl: 6.4-3
libpve-guest-common-perl: 3.1-5
libpve-http-server-perl: 3.2-3
libpve-storage-perl: 6.4-1
libqb0: 1.0.5-1
libspice-server1: 0.14.2-4~pve6+1
lvm2: 2.03.02-pve4
lxc-pve: 4.0.6-2
lxcfs: 4.0.6-pve1
novnc-pve: 1.1.0-1
proxmox-backup-client: 1.1.8-1
proxmox-mini-journalreader: 1.1-1
proxmox-widget-toolkit: 2.5-6
pve-cluster: 6.4-1
pve-container: 3.3-5
pve-docs: 6.4-2
pve-edk2-firmware: 2.20200531-1
pve-firewall: 4.1-4
pve-firmware: 3.2-4
pve-ha-manager: 3.1-1
pve-i18n: 2.3-1
pve-qemu-kvm: 5.2.0-6
pve-xtermjs: 4.7.0-3
qemu-server: 6.4-2
smartmontools: 7.2-pve2
spiceterm: 3.1-1
vncterm: 1.6-2
zfsutils-linux: 2.0.4-pve1`

**Comment by quotengrote** [comment]
warte mal noch, muss was testen

**Comment by quotengrote** [comment]
So...

# Problem
Bei PVE2 hat das Repo `deb http://download.proxmox.com/debian/pve buster pve-no-subscription` gefehlt.
Dadurch war der Paketstand unterschiedlich(`mg@RMPHLPVE1:~$ pveversion -v proxmox-ve: 6.4-1 (running kernel: 5.4.114-1-pve)` vs. `mg@RMPHLPVE2:~$ pveversion -v proxmox-ve: 6.0-2 (running kernel: 5.0.15-1-pve)`.

## Lösung
Nach einbauen des Repos und Updaten des Hosts tritt weder der Fehler bei Purge noch beim backup auf.

Die Problemlösung auch mit ins Forum schreiben @MaxGoe

**Comment by quotengrote** [comment]
Steht in Forum, mache zu.
